# Universal Windows Platform

# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64|ARM64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(System.DefaultWorkingDirectory)\AppxPackages'

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '84ac49ca-47e0-4979-b8ee-cd1cf8fe4e74'
    pipeline: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: CmdLine@2
  inputs:
    script: |
      move $(System.ArtifactsDirectory)\drop\install_amd64_rootfs.tar.gz x64\install.tar.gz
      move $(System.ArtifactsDirectory)\drop\install_arm64_rootfs.tar.gz ARM64\install.tar.gz
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DownloadSecureFile@1
  name: signingCert
  inputs:
    secureFile: 'store.pfx'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:Build /m /p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:PackageCertificateThumbprint=""  /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)" /p:PackageCertificatePassword="1"'
    platform: 'x64'
    configuration: '$(buildConfiguration)'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(appxPackageDir)'
    Contents: '**\*bundle.appxupload'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(appxPackageDir)'
    Contents: '**\*.appxbundle'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: store-publish@0
  continueOnError: true
  timeoutInMinutes: 10
  inputs:
    serviceEndpoint: 'Whitewater Foundry'
    appId: '9NV1GV1PXZ6P'
    metadataUpdateMethod: 'TextMetadata'
    metadataPath: '$(System.DefaultWorkingDirectory)\appMetadata'
    updateImages: false
    packagePath: '$(Build.ArtifactStagingDirectory)\**\*bundle.appxupload'
    force: true
    skipPolling: false
    deletePackages: true
    numberOfPackagesToKeep: '0'
- task: store-flight@0
  continueOnError: true
  inputs:
    serviceEndpoint: 'Whitewater Foundry'
    appId: '9NV1GV1PXZ6P'
    flightName: 'Azure Pipelines'
    packagePath: '$(Build.ArtifactStagingDirectory)\**\*bundle.appxupload'
    force: true
    skipPolling: false
    deletePackages: true
    numberOfPackagesToKeep: '0'
